### PR TITLE
Add basic API documentation

### LINKED ISSUE #35: Add basic API docs (sphinx)

### PR DESCRIPTION
**Pull request by rruuaanng**
Closes #35

### CODE REVIEW

**Review by skirpichev — COMMENTED** [review]
General notes.

1. please use autodoc; API entries should be taken from docstrings.
2. please don't use generated conf.py: include only customized options.
3. I don't think we need makefiles; using sphinx-build is fine.
4. Set up CI for docs (see e.g. mpmath).

**Comment by rruuaanng** [comment]
It seems that `API` can only be used for Python code, but we are using C.

**Comment by rruuaanng** [comment]
图片
WDYT?

**Comment by skirpichev** [comment]
> It seems that autodoc can only be used for Python code, but we are using C.

No, it should work for C extensions as well.  See e.g. gmpy2.

**Comment by rruuaanng** [comment]
Ok, I'm migrating object methods to `auto*` tags.

**Comment by rruuaanng** [comment]
I don't know what happened, but it seems that CI has not changed :(

**Comment by skirpichev** [comment]
Thanks for your work.

**Comment by rruuaanng** [comment]
> Thanks for your work.

That's for sure 👍

**Pull request closed without merging**
